# Generated by Django 6.1.1 on 2026-09-14 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0003_alter_todo_options_todo_user_alter_todo_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11, verbose_name='شماره همراه')),
                ('code_hash', models.CharField(max_length=128, verbose_name='هش کد تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
            ],
            options={
                'verbose_name': 'کد ورود پیامکی',
                'verbose_name_plural': 'کدهای ورود پیامکی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'is_used', 'expires_at'], name='otp_phone_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='شماره همراه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
    ]
