# Generated by Django 6.1.1 on 2026-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0005_category_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('low', 'پایین'), ('medium', 'متوسط'), ('high', 'بالا')], default='medium', max_length=10, verbose_name='اولویت'),
        ),
    ]
