# Generated by Django 6.1.1 on 2026-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0006_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'بدون تکرار'), ('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], default='none', max_length=10, verbose_name='تکرار'),
        ),
    ]
