# Generated by Django 6.1.1 on 2026-09-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0007_todo_repeat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_enabled',
            field=models.BooleanField(default=False, verbose_name='یادآوری فعال'),
        ),
    ]
