# Generated by Django 6.1.1 on 2026-09-16 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapplication', '0008_todo_reminder_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_todos', to=settings.AUTH_USER_MODEL, verbose_name='اشتراک\u200cگذاری شده با'),
        ),
    ]
